#ifndef _CH53_AIRFRAME_
#define _CH53_AIRFRAME_

#include "CH53SimModule.h"

namespace CH53
{
    class Airframe : public SimModule
    {
    public:
        enum IntegrityElement
        {
            NOSE_CENTER            = 0,
            FRONT                  = 0,
            Line_NOSE              = 0,
            NOSE_LEFT_SIDE         = 1,
            NOSE_RIGHT_SIDE        = 2,
            COCKPIT                = 3,
            CABINA                 = 3,
            CABIN_LEFT_SIDE        = 4,
            CABIN_RIGHT_SIDE       = 5,
            CABIN_BOTTOM           = 6,
            GUN                    = 7,
            FRONT_GEAR_BOX         = 8,
            GEAR_REAR              = 8,
            GEAR_C                 = 8,
            GEAR_F                 = 8,
            STOIKA_F               = 8,
            GEAR_FRONT             = 8,
            FUSELAGE_LEFT_SIDE     = 9,
            FUSELAGE_RIGHT_SIDE    = 10,
            MAIN                   = 10,
            Line_MAIN              = 10,
            ENGINE                 = 11,
            ENGINE_L               = 11,
            ENGINE_L_VNUTR         = 11,
            ENGINE_L_IN            = 11,
            ENGINE_R               = 12,
            ENGINE_R_VNUTR         = 12,
            ENGINE_R_IN            = 12,
            MTG_L_BOTTOM           = 13,
            MTG_R_BOTTOM           = 14,
            LEFT_GEAR_BOX          = 15,
            GEAR_L                 = 15,
            STOIKA_L               = 15,
            RIGHT_GEAR_BOX         = 16, 
            GEAR_R                 = 16,
            STOIKA_R               = 16,
            MTG_L                  = 17,
            ENGINE_L_VNESHN        = 17,
            ENGINE_L_OUT           = 17,
            EWU_L                  = 17,
            MTG_R                  = 18,
            ENGINE_R_VNESHN        = 18,
            ENGINE_R_OUT           = 18,
            EWU_R                  = 18,
            AIR_BRAKE_L            = 19,
            AIR_BRAKE_R            = 20,
            WING_L_PART_OUT        = 21,
            WING_R_PART_OUT        = 22,
            WING_L_OUT             = 23,
            WING_R_OUT             = 24,
            ELERON_L               = 25,
            AILERON_L              = 25,
            ELERON_R               = 26,
            AILERON_R              = 26,
            WING_L_PART_CENTER     = 27,
            WING_R_PART_CENTER     = 28,
            WING_L_CENTER          = 29,
            WING_R_CENTER          = 30,
            FLAP_L_OUT             = 31,
            FLAP_R_OUT             = 32,
            WING_L_PART_IN         = 33,
            WING_R_PART_IN         = 34,
            WING_L_IN              = 35,
            WING_L                 = 35,
            Line_WING_L            = 35,
            WING_R_IN              = 36,
            WING_R                 = 36,
            Line_WING_R            = 36,
            FLAP_L_IN              = 37,
            FLAP_L                 = 37,
            FLAP_R_IN              = 38,
            FLAP_R                 = 38,
            FIN_L_TOP              = 39,
            KEEL_L_OUT             = 39,
            KEEL_OUT               = 39,
            FIN_R_TOP              = 40,
            KEEL_R_OUT             = 40,
            FIN_L_CENTER           = 41,
            KEEL_L_CENTER          = 41,
            KEEL_CENTER            = 41,
            FIN_R_CENTER           = 42,
            KEEL_R_CENTER          = 42,
            FIN_L_BOTTOM           = 43,
            KIL_L                  = 43,
            Line_KIL_L             = 43,
            KEEL                   = 43,
            KEEL_IN                = 43,
            KEEL_L                 = 43,
            KEEL_L_IN              = 43,
            FIN_R_BOTTOM           = 44,
            KIL_R                  = 44,
            Line_KIL_R             = 44,
            KEEL_R                 = 44,
            KEEL_R_IN              = 44,
            STABILIZER_L_OUT       = 45,
            STABILIZATOR_L_OUT     = 45,
            STABILIZER_R_OUT       = 46,
            STABILIZATOR_R_OUT     = 46,
            STABILIZER_L_IN        = 47,
            STABILIZATOR_L         = 47,
            STABILIZATOR_L01       = 47,
            Line_STABIL_L          = 47,
            STABILIZER_R_IN        = 48,
            STABILIZATOR_R         = 48,
            STABILIZATOR_R01       = 48,
            Line_STABIL_R          = 48,
            ELEVATOR_L_OUT         = 49,
            ELEVATOR_R_OUT         = 50,
            ELEVATOR_L_IN          = 51,
            ELEVATOR_L             = 51,
            RV_L                   = 51,
            ELEVATOR_R_IN          = 52,
            ELEVATOR_R             = 52,
            RV_R                   = 52,
            RUDDER_L               = 53,
            RN_L                   = 53,
            RUDDER                 = 53,
            RUDDER_R               = 54,
            RN_R                   = 54,
            TAIL                   = 55,
            TAIL_LEFT_SIDE         = 56,
            TAIL_RIGHT_SIDE        = 57,
            TAIL_BOTTOM            = 58,
            NOSE_BOTTOM            = 59,
            PWD                    = 60,
            PITOT                  = 60,
            FUEL_TANK_F            = 61,
            FUEL_TANK_LEFT_SIDE    = 61,
            FUEL_TANK_B            = 62,
            FUEL_TANK_RIGHT_SIDE   = 62,
            ROTOR                  = 63,
            BLADE_1_IN             = 64,
            BLADE_1_CENTER         = 65,
            BLADE_1_OUT            = 66,
            BLADE_2_IN             = 67,
            BLADE_2_CENTER         = 68,
            BLADE_2_OUT            = 69,
            BLADE_3_IN             = 70,
            BLADE_3_CENTER         = 71,
            BLADE_3_OUT            = 72,
            BLADE_4_IN             = 73,
            BLADE_4_CENTER         = 74,
            BLADE_4_OUT            = 75,
            BLADE_5_IN             = 76,
            BLADE_5_CENTER         = 77,
            BLADE_5_OUT            = 78,
            BLADE_6_IN             = 79,
            BLADE_6_CENTER         = 80,
            BLADE_6_OUT            = 81,
            FUSELAGE_BOTTOM        = 82,
            WHEEL_F                = 83,
            WHEEL_C                = 83,
            WHEEL_REAR             = 83,
            WHEEL_FRONT            = 83,
            WHEEL_L                = 84,
            WHEEL_R                = 85,
            PYLON1                 = 86,
            PYLONL                 = 86,
            PYLON2                 = 87,
            PYLONR                 = 87,
            PYLON3                 = 88,
            PYLON4                 = 89,
            CREW_1                 = 90,
            CREW_2                 = 91,
            CREW_3                 = 92,
            CREW_4                 = 93,
            ARMOR_NOSE_PLATE_LEFT  = 94,
            ARMOR_NOSE_PLATE_RIGHT = 95,
            ARMOR_PLATE_LEFT       = 96,
            ARMOR_PLATE_RIGHT      = 97,
            HOOK                   = 98,
            FUSELAGE_TOP           = 99,
            TAIL_TOP               = 100,
            FLAP_L_CENTER          = 101,
            FLAP_R_CENTER          = 102,
            ENGINE_1               = 103,
            ENGINE_2               = 104,
            ENGINE_3               = 105,
            ENGINE_4               = 106,
            ENGINE_5               = 107,
            ENGINE_6               = 108,
            ENGINE_7               = 109,
            ENGINE_8               = 110,
            WING_L_00              = 111,
            WING_L_01              = 112,
            WING_L_02              = 113,
            WING_L_03              = 114,
            WING_L_04              = 115,
            WING_L_05              = 116,
            WING_L_06              = 117,
            WING_L_07              = 118,
            WING_L_08              = 119,
            WING_L_09              = 120,
            WING_L_10              = 121,
            WING_L_11              = 122,
            WING_R_00              = 123,
            WING_R_01              = 124,
            WING_R_02              = 125,
            WING_R_03              = 126,
            WING_R_04              = 127,
            WING_R_05              = 128,
            WING_R_06              = 129,
            WING_R_07              = 130,
            WING_R_08              = 131,
            WING_R_09              = 132,
            WING_R_10              = 133,
            WING_R_11              = 134,
            LAUNCH_BAR             = 135,
            COUNT                  = 136,
        };
        enum ForceComponent
        {
            AIRFRAME_DRAG                     = 0,
            AIRFRAME_MAX_NUM_FORCE_COMPONENTS,
        };

    protected:
        // damage status of section in 0.01 increments
        double elementIntegrity[IntegrityElement::COUNT] = {0}; // store each damage element 
        bool   isImmortal; // <- ignore damage

    public:
        static constexpr double inertia_Ix_KGM2         = 55076.0;		// Reference moment of inertia (kg/m^2) 446.0;
        static constexpr double inertia_Iy_KGM2         = 267549.0;		// Reference moment of inertia (kg/m^2) 1219.6;
        static constexpr double inertia_Iz_KGM2         = 284943.0;		// Reference moment of inertia (kg/m^2) 979.1;
        static constexpr double crossSectionArea_M2_x   = 8.2;
        static constexpr double crossSectionArea_M2_y   = 24.0; 
        static constexpr double crossSectionArea_M2_z   = 34.0;


        double rotorIntegrityFactor; // basic damage model to decrease lift if blades are missing
        double tailRotorIntegrityFactor;

        Airframe();
        virtual ~Airframe();
        virtual void vInit(bool hotStart, bool inAir);
        virtual void vRelease();
        // Scripts\Aircrafts\_Common\Damage.lua	 for element numbers
        virtual void onAirframeDamage(int IntegrityElement, double element_integrity_factor);
        virtual void onRepair();
        virtual bool isRepairNeeded() const;
        virtual void setImmortal(bool value);
        virtual void vSimulate(struct Systems& systems, EDPARAM& cockpitAPI, double dt);
    };
}

#endif //_CH53_AIRFRAME_